{"name": "test_validLogin", "status": "broken", "statusDetails": {"message": "AttributeError: 'CustomLogger' object has no attribute 'info'", "trace": "self = <pages.LoginPage.LoginPage object at 0x0000016AA0B8EA50>, text = '9999999999', locatorValue = '//android.widget.EditText'\nlocatorType = 'xpath'\n\n    def SendKeys(self,text, locatorValue, locatorType=\"id\"):\n        element = None\n        try:\n            locatorType = locatorType.lower()\n            element = self.waitForElement(locatorValue, locatorType)\n            element.send_keys(text)\n>           self.log.info(\"Send a text with locator type\" + locatorType + \"with locator value\" + locatorValue)\nE           AttributeError: 'CustomLogger' object has no attribute 'info'\n\n..\\base\\BasePage.py:99: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.LoginTest.LoginTest testMethod=test_validLogin>\n\n    @pytest.mark.run(order=1)\n    def test_validLogin(self):\n>       self.lp.enterPhoneNumber()\n\nLoginTest.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\LoginPage.py:23: in enterPhoneNumber\n    self.SendKeys(\"9999999999\",self._enterPhoneNumer,\"xpath\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.LoginPage.LoginPage object at 0x0000016AA0B8EA50>, text = '9999999999', locatorValue = '//android.widget.EditText'\nlocatorType = 'xpath'\n\n    def SendKeys(self,text, locatorValue, locatorType=\"id\"):\n        element = None\n        try:\n            locatorType = locatorType.lower()\n            element = self.waitForElement(locatorValue, locatorType)\n            element.send_keys(text)\n            self.log.info(\"Send a text with locator type\" + locatorType + \"with locator value\" + locatorValue)\n    \n        except:\n>           self.log.info(\"Unable to send the text with locator type\" + locatorType + \"with locator value\" + locatorValue)\nE           AttributeError: 'CustomLogger' object has no attribute 'info'\n\n..\\base\\BasePage.py:102: AttributeError"}, "attachments": [{"name": "log", "source": "160453fa-d89b-41f4-90d3-066703406bf4-attachment.txt", "type": "text/plain"}], "start": 1739959786352, "stop": 1739959787867, "uuid": "e020aa23-6055-4254-8e87-af14dfef1e99", "historyId": "6d485cd84f8cf430b8322063143bb42e", "testCaseId": "6d485cd84f8cf430b8322063143bb42e", "fullName": "LoginTest.LoginTest#test_validLogin", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "suite", "value": "LoginTest"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "Chinmayi"}, {"name": "thread", "value": "8476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "LoginTest"}]}