{"name": "test_loginfail", "status": "broken", "statusDetails": {"message": "AttributeError: 'function' object has no attribute 'allureLogs'", "trace": "self = <tests.test_login.test_login testMethod=test_loginfail>\n\n    @pytest.mark.run(order=2)\n    def test_loginfail(self):\n        #cl.allureLogs(\"App Launched\")\n>       self.lp.enterPhoneNumber()\n\ntest_login.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.LoginPage.LoginPage object at 0x0000026B9848FC50>\n\n    def enterPhoneNumber(self):\n        self.SendKeys(\"9999999999\",self._enterPhoneNumer,\"xpath\")\n>       cl.allureLogs(\"Entered Phone Number\")\nE       AttributeError: 'function' object has no attribute 'allureLogs'\n\n..\\pages\\LoginPage.py:22: AttributeError"}, "attachments": [{"name": "log", "source": "0c785f48-93d0-44fd-b91a-fa64f2ef2625-attachment.txt", "type": "text/plain"}], "start": 1739876671148, "stop": 1739876672218, "uuid": "10a1df77-0f8d-46a2-92a4-811c500cc193", "historyId": "b564db8fe7180511f5c38870cd3f148d", "testCaseId": "b564db8fe7180511f5c38870cd3f148d", "fullName": "test_login.test_login#test_loginfail", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "test_login"}, {"name": "host", "value": "Chinmayi"}, {"name": "thread", "value": "4028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}