{"name": "test_loginfail", "status": "broken", "statusDetails": {"message": "AttributeError: 'function' object has no attribute 'allureLogs'", "trace": "self = <tests.LoginTest.LoginTest testMethod=test_loginfail>\n\n    @pytest.mark.run(order=2)\n    def test_loginfail(self):\n>       cl.allureLogs(\"App Launched\")\nE       AttributeError: 'function' object has no attribute 'allureLogs'\n\nLoginTest.py:30: AttributeError"}, "start": 1739940964037, "stop": 1739940964037, "uuid": "8e390e17-5e41-4b47-a526-3dd596ae794b", "historyId": "2e9d26c442f09a305fb336d897266e93", "testCaseId": "2e9d26c442f09a305fb336d897266e93", "fullName": "LoginTest.LoginTest#test_loginfail", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "suite", "value": "LoginTest"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "Chinmayi"}, {"name": "thread", "value": "15112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "LoginTest"}]}